-- MySQL Script generated by MySQL Workbench
-- Qui 15 Set 2016 16:02:07 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso` DEFAULT CHARACTER SET latin1 ;
USE `curso` ;

-- -----------------------------------------------------
-- Table `curso`.`agente_qualificador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`agente_qualificador` (
  `idagente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idagente`, `nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `curso`.`cadPessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`cadPessoas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dataInscricao` DATE NULL DEFAULT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_nascimento` VARCHAR(40) NULL DEFAULT NULL,
  `idade` INT(5) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(40) NULL DEFAULT NULL,
  `local_nasc` VARCHAR(80) NULL DEFAULT NULL,
  `rg` VARCHAR(20) NULL DEFAULT NULL,
  `rg_orgEmissor` VARCHAR(20) NULL DEFAULT NULL,
  `rg_data` VARCHAR(40) NULL DEFAULT NULL,
  `pai` VARCHAR(60) NULL DEFAULT NULL,
  `mae` VARCHAR(60) NULL DEFAULT NULL,
  `endereco` VARCHAR(80) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `bairro` VARCHAR(80) NULL DEFAULT NULL,
  `cidade` VARCHAR(80) NULL DEFAULT NULL,
  `cep` CHAR(20) NULL DEFAULT NULL,
  `fone` CHAR(14) NULL DEFAULT NULL,
  `celular` CHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `pcd` VARCHAR(10) NULL DEFAULT NULL,
  `qual_pcd` VARCHAR(120) NULL DEFAULT NULL,
  `escolaridade` VARCHAR(40) NULL DEFAULT NULL,
  `cursos_qualificacao` VARCHAR(80) NULL DEFAULT NULL,
  `observacao` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `curso`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`cursos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `requisito` VARCHAR(255) NULL DEFAULT NULL,
  `carga_horaria` SMALLINT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `nome`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `curso`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`turmas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_turma` VARCHAR(45) NOT NULL,
  `cursos_id` INT(10) UNSIGNED NOT NULL,
  `agente_qualificador_idagente` INT(11) NOT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `data_final` DATE NULL DEFAULT NULL,
  `minimo_alunos` INT(10) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `turmas_FKIndex1` (`cursos_id` ASC),
  INDEX `fk_turmas_agente_qualificador1_idx` (`agente_qualificador_idagente` ASC),
  CONSTRAINT `fk_turmas_agente_qualificador1`
    FOREIGN KEY (`agente_qualificador_idagente`)
    REFERENCES `curso`.`agente_qualificador` (`idagente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `turmas_ibfk_1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `curso`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `curso`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`matriculas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `turmas_id` INT(10) UNSIGNED NOT NULL,
  `data_inscricao` DATE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `cadPessoas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `matriculas_FKIndex3` (`turmas_id` ASC),
  INDEX `fk_matriculas_cadPessoas1_idx` (`cadPessoas_id` ASC),
  CONSTRAINT `fk_matriculas_cadPessoas1`
    FOREIGN KEY (`cadPessoas_id`)
    REFERENCES `curso`.`cadPessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `matriculas_ibfk_2`
    FOREIGN KEY (`turmas_id`)
    REFERENCES `curso`.`turmas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
